apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: demo-deployment
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: test-pv
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
      volumes:
        - name: test-pv
          persistentVolumeClaim:
            claimName: my-demo-volume